import { B2Vec2, B2Vec3, B2Mat33, B2Rot } from '../../Common/b2Math';
import { B2Body } from '../b2Body';
import { B2Joint, B2JointDef } from './b2Joint';
import { B2SolverData } from '../b2TimeStep';
export declare class B2WeldJointDef extends B2JointDef {
    localAnchorA: B2Vec2;
    localAnchorB: B2Vec2;
    referenceAngle: number;
    frequencyHz: number;
    dampingRatio: number;
    constructor();
    Initialize(bA: B2Body, bB: B2Body, anchor: B2Vec2): void;
}
export declare class B2WeldJoint extends B2Joint {
    m_frequencyHz: number;
    m_dampingRatio: number;
    m_bias: number;
    m_localAnchorA: B2Vec2;
    m_localAnchorB: B2Vec2;
    m_referenceAngle: number;
    m_gamma: number;
    m_impulse: B2Vec3;
    m_indexA: number;
    m_indexB: number;
    m_rA: B2Vec2;
    m_rB: B2Vec2;
    m_localCenterA: B2Vec2;
    m_localCenterB: B2Vec2;
    m_invMassA: number;
    m_invMassB: number;
    m_invIA: number;
    m_invIB: number;
    m_mass: B2Mat33;
    m_qA: B2Rot;
    m_qB: B2Rot;
    m_lalcA: B2Vec2;
    m_lalcB: B2Vec2;
    m_K: B2Mat33;
    constructor(def: B2WeldJointDef);
    private static InitVelocityConstraints_s_P;
    InitVelocityConstraints(data: B2SolverData): void;
    private static SolveVelocityConstraints_s_Cdot1;
    private static SolveVelocityConstraints_s_impulse1;
    private static SolveVelocityConstraints_s_impulse;
    private static SolveVelocityConstraints_s_P;
    SolveVelocityConstraints(data: B2SolverData): void;
    private static SolvePositionConstraints_s_C1;
    private static SolvePositionConstraints_s_P;
    private static SolvePositionConstraints_s_impulse;
    SolvePositionConstraints(data: B2SolverData): boolean;
    GetAnchorA(out: B2Vec2): B2Vec2;
    GetAnchorB(out: B2Vec2): B2Vec2;
    GetReactionForce(inv_dt: number, out: B2Vec2): B2Vec2;
    GetReactionTorque(inv_dt: number): number;
    GetLocalAnchorA(): B2Vec2;
    GetLocalAnchorB(): B2Vec2;
    GetReferenceAngle(): number;
    SetFrequency(hz: number): void;
    GetFrequency(): number;
    SetDampingRatio(ratio: number): void;
    GetDampingRatio(): number;
    Dump(log: (format: string, ...args: any[]) => void): void;
}
